name: Sync Ilios Calendar

on:
  schedule:
    - cron: '0 6 * * *'    # daily at 6 AM UTC
  workflow_dispatch:      # manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests icalendar google-auth google-auth-oauthlib google-api-python-client

      - name: Write Google credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > credentials.json

      - name: Run full sync
        env:
          ILIOS_ICS_URL:      ${{ vars.ILIOS_ICS_URL }}
          SYNCED_CALENDAR_ID: ${{ vars.SYNCED_CALENDAR_ID }}
        run: |
          python full_sync3.py

      - name: Commit & push updated .ics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ilios_full.ics
          git commit -m "Auto-update ilios_full.ics" || echo "No changes"
          git push
